# Generated by Django 3.1.3 on 2020-11-08 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[mainapp.validators.validate_date])),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='eliminationround',
            name='num_of_teams',
        ),
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='elimination_phase',
        ),
        migrations.AddField(
            model_name='eliminationphase',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.tournament'),
        ),
        migrations.AddField(
            model_name='eliminationround',
            name='isCurrent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eliminationround',
            name='num_of_games',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='matches_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='num_of_teams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='isPlayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='nextMatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.match'),
        ),
        migrations.AddField(
            model_name='participation',
            name='goal_diff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='goals_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participation',
            name='goals_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participation',
            name='num_of_draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='lastname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(default=9, verbose_name=range(1, 99)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='pin',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='scorer',
            name='minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='applications_open_until',
            field=models.DateField(blank=True, null=True, validators=[mainapp.validators.validate_date]),
        ),
        migrations.AddField(
            model_name='tournament',
            name='bronzer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bronzer', to='mainapp.team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='isGenerated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='runner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runner', to='mainapp.team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, null=True, validators=[mainapp.validators.validate_date]),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='mainapp.team'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/profiles/default_img.jpg', upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='registered',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='eliminationround',
            name='elimination_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.eliminationphase'),
        ),
        migrations.AlterField(
            model_name='match',
            name='elimination_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.eliminationround'),
        ),
        migrations.AlterField(
            model_name='match',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.group'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='mainapp.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='mainapp.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='num_of_defeats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participation',
            name='num_of_played_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participation',
            name='num_of_victories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participation',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, default='players/player.png', null=True, upload_to='players/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='scorer',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.match'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default='teams/team.png', upload_to='teams/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='num_of_apps',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='num_of_groups',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='num_of_teams',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='teams_promoted',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('lastUpTime', models.DateTimeField(auto_now=True)),
                ('lastUpUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastupuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.tournament')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.matchdate'),
        ),
        migrations.AddField(
            model_name='user',
            name='reputation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.reputation'),
        ),
    ]
