"""
Django settings for TournamentManager project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import dj_database_url
import django_heroku
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'tournamentmanager12.herokuapp.com']


TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mainapp',
]

TEMPLATE_CONTEXT_PROCESSORS = (
  'django.core.context_processors.request',
)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TournamentManager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['TEMPLATE_DIR'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TournamentManager.wsgi.application'

# Simplified static file serving.


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

AUTH_USER_MODEL = 'mainapp.User'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/mainapp/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

LOGIN_REDIRECT_URL = '/'

DATETIME_INPUT_FORMATS = (
    '%d %B %Y - %H:%M:%S.%f',  # '05 March 2014 - 08:07:59.0001'
    '%d %B %Y - %H:%M:%S',     # '05 March 2014 - 08:07:59'
    '%d %B %Y - %H:%M',        # '05 March 2014 - 08:07'
    '%d %B %Y',                # '05 March 2014' <- this line was first before

    '%d/%m/%Y %H:%M:%S.%f',    # '25/10/05 14:30:59.000200'
    '%d/%m/%Y %H:%M:%S',       # '25/10/05 14:30:59'
    '%d/%m/%Y %H:%M',          # '25/10/05 14:30'
    '%d/%m/%Y',                # '25/10/05'

    '%d-%m-%Y %H:%M:%S.%f',    # '25-10-05 14:30:59.000200'
    '%d-%m-%Y %H:%M:%S',       # '25-10-05 14:30:59'
    '%d-%m-%Y %H:%M',          # '25-10-05 14:30'
    '%d-%m-%Y',                # '25-10-05'

    '%Y-%m-%d %H:%M:%S.%f',    # '2006-10-25 14:30:59.000200'
    '%Y-%m-%d %H:%M:%S',       # '2006-10-25 14:30:59'
    '%Y-%m-%d %H:%M',          # '2006-10-25 14:30'
    '%Y-%m-%d',                # '2006-10-25'

    '%m/%d/%Y %H:%M:%S.%f',    # '10/25/2006 14:30:59.000200'
    '%m/%d/%Y %H:%M:%S',       # '10/25/2006 14:30:59'
    '%m/%d/%Y %H:%M',          # '10/25/2006 14:30'
    '%m/%d/%Y',                # '10/25/2006'

    '%m/%d/%y %H:%M:%S.%f',    # '10/25/06 14:30:59.000200'
    '%m/%d/%y %H:%M:%S',       # '10/25/06 14:30:59'
    '%m/%d/%y %H:%M',          # '10/25/06 14:30'
    '%m/%d/%y',                # '10/25/06'
)
LOGOUT_REDIRECT_URL = '/'
TIME_ZONE='Europe/Zagreb'

EMAIL_HOST=os.getenv('EMAIL_HOST')
EMAIL_HOST_USER=os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD=os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS=True
EMAIL_PORT=os.getenv('EMAIL_HOST_PORT')
django_heroku.settings(locals())
